services:
  - type: web
    name: instalogo-bot
    env: node
    runtime: node
    region: oregon
    plan: starter
    buildCommand: npm ci && npm run build
    startCommand: npm start
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: WEBHOOK_URL
        value: https://instalogo-bot.onrender.com/webhook/${BOT_TOKEN}
      - key: PORT
        value: 3000
      # Add your other environment variables in Render dashboard:
      # BOT_TOKEN, MONGODB_URI, CLOUDINARY_CLOUD_NAME, etc.
    autoDeploy: true
    branch: main
    rootDir: .

    # Health check configuration
    healthCheck:
      path: /health
      interval: 30s
      timeout: 10s
      retries: 3

    # Auto-scaling configuration
    scaling:
      minInstances: 1
      maxInstances: 3
      targetCPU: 70
      targetMemory: 80
